### ISSUE TITLE
Working on web scrapping and check whether it is allowed or not.

### ISSUE THREAD

**Issue by Sreyas-Reddy-Mallypally** [s546652/GDP-1-Project_Team_1#7]

**Comment by Sreyas-Reddy-Mallypally** [comment]
We meet publications department and need to meet technical department members as they don't have any API, so need to work on web scrapping and see how far can it be considered.

**Comment by Sreyas-Reddy-Mallypally** [comment]
Tried doing web scraping with python and was successfully able to get the data in html format. Now working on how to getting the click actions so that we can get end to end data for user interactions.

Committed the working code for web scraping into repo.

**Comment by s546652** [comment]
Worked on how to web scraping using swift and found a way using NSURL . Below is the code link with which we were able to fetch the data.
[Link ](https://github.com/s546652/GDP-1-Project_Team_1/blob/main/Web%20Scraping/Webscrap_swift.md)

**Comment by Sreyas-Reddy-Mallypally** [comment]
Completed working on the web scrapping and the only left-out part is doing server killing or using EC2.
